### ISSUE TITLE
V1.0.11 has am empty lib directory

### ISSUE THREAD

**Issue by franckLdx** [Soluto/testcafe-reporter-teamcity#8]
I tried to used the v1.0.11, but I couldn't. It appears that lib directory of v1.0.11 is empty.

**Comment by aaron-goff** [comment]
Is there any investigation into fixing this? Definitely a bad look if the version installed with the instructions in the README are just broken.

Anyone reading this, in order to properly use this library, use `npm install testcafe-reporter-teamcity@1.0.10` instead of just `npm install testcafe-reporter-teamcity`

**Comment by konwinkler** [comment]
I wanted to give this issue a bump since it is very likely for anyone to setup TestCafe in TeamCity to run into this. 

@noamokman

**Comment by noamokman** [comment]
Fixed 👍

**Comment by konwinkler** [comment]
Awesome, thank you 🎊
